#!/usr/bin/python3
import requests
import sys
import socket

from requests.exceptions import Timeout


ip =  str(sys.argv[1])


def ipLkup(ip):

    req = 'http://ip-api.com/json/{}'.format(ip)
    
    try:

        r = requests.get(req,timeout=4)
    except requests.exceptions.Timeout:
        print("Timeout :(")
        exit()

    except requests.exceptions.RequestException :
        print("error :(")    
        exit()
    # print(r.json())
    # print(r.status_code)



    #checking the status from the API 
    if r.json()['status'] == "fail":
        print("\t")
        print("\tRequest failed \n\tInvalid query :{}".format(ip))
    else:
        print("\t----------------------------")
        print("\tISP     :: {}".format(r.json()['isp']))
        print("\tORG     :: {}".format(r.json()['org']))
        print("\tCountry :: {}".format(r.json()['country']))
        print("\tH_name  :: {}".format(socket.getfqdn(ip)))
        print("\t----------------------------")
    # print("\n")


ipLkup(ip)
